Clean files in local_modules
brown-ccv/icesat2waves pull request #131
Opened 2024-02-26 16:32 UTC by kmilo9999

- Cleaning and formatting files in `local_modules `folder

2024-02-26 16:55 UTC, hollandjg requested changes
Hi Camilo! I've a couple of things I'd reintroduce (units on physical values) but otherwise this looks good!

2024-02-26 16:55 UTC, hollandjg commented on src/icesat2_tracks/local_modules/JONSWAP_gamma.py
> +    alpha = 0.076 * (g * X / U**2) ** (-0.22)
I think I'd leave the comment here – it's not code, it's the (dimensionless) units of alpha.

2024-02-26 16:55 UTC, hollandjg commented on src/icesat2_tracks/local_modules/JONSWAP_gamma.py
> +    alpha = 0.076 * (g * X / U**2) ** (-0.22)
```suggestion
    alpha = 0.076 * (g * X / U**2) ** (-0.22)  # dimensionless
```

2024-02-26 16:55 UTC, hollandjg commented on src/icesat2_tracks/local_modules/JONSWAP_gamma.py
> +    w = 2.0 * np.pi * f
```suggestion
    w = 2.0 * np.pi * f  # rad/sec 
```

2024-02-26 16:55 UTC, hollandjg commented on src/icesat2_tracks/local_modules/JONSWAP_gamma.py
> +    )
Same here – this is useful for someone reading the code
```suggestion
    )  # Hz**-5 m**2 /s**4 = m**2 sec ?
```

2024-02-26 20:11 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/JONSWAP_gamma.py
> +    alpha = 0.076 * (g * X / U**2) ** (-0.22)
Comment added

2024-02-26 20:11 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/JONSWAP_gamma.py
> +    w = 2.0 * np.pi * f
Comment added

2024-02-26 20:11 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/JONSWAP_gamma.py
> +    alpha = 0.076 * (g * X / U**2) ** (-0.22)
Comment added

2024-02-26 22:48 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
There are number of import statements that could be moved to the top of the file.

2024-02-26 22:51 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
>  class moments:
This class should be renamed `Moments` per [PEP 8](https://peps.python.org/pep-0008/#class-names).

2024-02-26 22:52 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
>  class pwelch:
Rename class as per PEP 8?

2024-02-27 14:34 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/JONSWAP_gamma.py
> +    w = 2.0 * np.pi * f
added comment

2024-02-27 16:34 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
Moved all the import top he top of the file

2024-02-27 16:34 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
>  class moments:
Renamed

2024-02-27 16:34 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
>  class pwelch:
Renamed

2024-02-27 20:37 UTC, hollandjg requested changes
One final set of changes – otherwise looks good!

2024-02-27 20:37 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +import datetime as DT
I think we might want to just leave the name `datetime` as is – `DT` seems more like a constant name than a module name. I think it's fine that we have `datetime.datetime.now()` below.

An alternative is to do `from datetime import datetime` and then you'd have calls like `datetime.now()` and `type(datetime)` below.

2024-02-27 21:42 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +import datetime as DT
Done

2024-02-28 19:49 UTC, hollandjg submitted a review, later dismissed
Awesome! 🚀

2024-02-28 21:12 UTC, cpaniaguam requested changes
I meant to send this yesterday. Consider seeing if there's any relevant left!

2024-02-28 21:12 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_colormanager_ph3.py
There are imports that can be moved to the top here.

2024-03-01 13:03 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
>          from m_general_ph3 import echo_dt
imports moved to the top of the file

2024-03-01 13:03 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
>  class save_data_periodogram:
renamed classes following PEP 8 standards

2024-03-01 13:04 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_colormanager_ph3.py
Moved imports to top of the file

2024-03-01 13:04 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
>  class Spectogram_subsample(pwelch):
renamed as requested

2024-03-01 15:30 UTC, hollandjg approved these changes
Looks good to me!

2024-03-01 18:34 UTC, kmilo9999 commented
all good here @cpaniaguam ?

2024-03-01 21:56 UTC, cpaniaguam approved these changes
I am approving but added a bunch of extra suggestions.

2024-03-01 21:56 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        self.length = -self.span[0] + self.span[1]
```suggestion
        self.length = self.span[1] - self.span[0] 
```

2024-03-01 21:56 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +            if path is not None
```suggestion
            if path
```

2024-03-01 21:56 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
>  def set_timeaxis_days(ax, int1=1, int2=2, bymonthday=None):
```suggestion
def set_timeaxis_days(ax, int1=1, int2=2, bymonthday=range(1, 32)):
```

2024-03-01 21:56 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +    bymonthday = bymonthday if bymonthday is not None else range(1, 32)
Delete this line if default value is set in function signature.
```suggestion
```

2024-03-01 21:56 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        self.ylim = ylim if ylim is not None else [fs[0], fs[-1]]
```suggestion
class PlotPeriodogram:
    def __init__(
        self,
        time,
        fs,
        data,
        clevs=None,
        sample_unit="df",
        data_unit="X",
        ylim=[fs[0], fs[-1]],
        time_unit="dt",
        cmap=plt.cm.ocean_r,
    ):
        self.fs = fs[1:]
        self.time = time
        self.data = data[:, 1:]
        self.clevs = clevs
        self.sample_unit = sample_unit

        self.data_unit = data_unit
        self.time_unit = time_unit

        self.cmap = cmap
        self.ylim = ylim
```

2024-03-01 21:56 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        self, f, thetas, data, unit=None, data_type="fraction", lims=None, verbose=False
```suggestion
        self, f, thetas, data, unit="X", data_type="fraction", lims=None, verbose=False
```

2024-03-01 21:56 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +    dstep = dstep if dstep is not None else 21
```suggestion
def clevels(data, dstep=21, symmetric=False):
```

2024-03-01 21:56 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        if dt is not None:
```suggestion
        if dt:
```

2024-03-01 21:56 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +    import sklearn.bootstrap as boot  # might not work in python 3
Move import to the top?

2024-03-01 21:56 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
>      #a = np.arange(1,361).T
```suggestion
```

2024-03-01 21:56 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +    b = "%2.1e" % high
Old style formatting.
```suggestion
    a = f"{low:.1e}"
    b = f"{high:.1e}"
```

2024-03-01 21:56 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +    return a[0:3] + "-" + b + " Hz"
```suggestion
    return f"{a[0:3]}-{b} Hz"
```

2024-03-01 21:56 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
>          return False
```suggestion
return a == ref
```

2024-03-01 21:56 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +    return "\n".join(f)
```suggestion
    f = []
        for h in glob.glob(os.path.join(path, hist_file_name)):
            with open(h, "r") as file:
                f.append(file.read())
    return "\n".join(f)
```

2024-03-01 21:56 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
>  def load_log_txt(name, path):
```suggestion
def load_log_txt(hist_file_name, path):
```

2024-03-04 15:47 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +    return "\n".join(f)
file re-formatted

2024-03-04 15:47 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
>          return False
done

2024-03-04 15:47 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +    return a[0:3] + "-" + b + " Hz"
file re-formatted

2024-03-04 15:47 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +    b = "%2.1e" % high
file re-formatted

2024-03-04 15:47 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
>      #a = np.arange(1,361).T
Removed

2024-03-04 15:47 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +    import sklearn.bootstrap as boot  # might not work in python 3
I added a comment on top of this line with some awareness on what happened to that import

2024-03-04 15:48 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        if dt is not None:
Done

2024-03-04 15:48 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +    dstep = dstep if dstep is not None else 21
Done

2024-03-04 15:48 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        self.ylim = ylim if ylim is not None else [fs[0], fs[-1]]
I made a small adjustment to your suggested code. The argument `ylimit` was being defined in terms of another argument

2024-03-04 15:48 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +    bymonthday = bymonthday if bymonthday is not None else range(1, 32)
Done

2024-03-04 15:48 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
>  def set_timeaxis_days(ax, int1=1, int2=2, bymonthday=None):
Done

2024-03-04 15:48 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +            if path is not None
Done

2024-03-04 15:49 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
>      if verbose is True:
Done

2024-03-04 15:49 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
>      if verbose is True:
Done

2024-03-04 15:49 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +            if nopower is True:
Done

2024-03-04 15:49 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +                if nopower is True:
Done

2024-03-04 15:49 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
>                  if nopower is True:
Done

2024-03-04 15:49 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        fig_size = [10, 4] if fig_size is None else fig_size
Done

2024-03-04 15:50 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        if anomalie is True:
Done

2024-03-04 15:50 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        if nopower is True:
Done

2024-03-04 15:50 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +            if nopower is True:
Done

2024-03-04 15:50 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        if cbar is True:
Done

2024-03-04 15:50 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        if anomalie is True:
Done

2024-03-04 15:51 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        if anomalie is True:
Done

2024-03-04 15:51 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        if nopower is True:
Done

2024-03-04 15:51 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +            print("save with: ", name)
I opened a new issue

2024-03-04 15:53 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        self.label_letters = iter([i + ") " for i in list(string.ascii_lowercase)])
let's leave it. I dont see a potential crash on production just for this line.

2024-03-04 15:53 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/JONSWAP_gamma.py
>      exec(open(STARTUP_2019_DP).read())
removed

2024-03-04 15:53 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        # ax1.set_xticks([20, 300, 500])
Removed commented code

2024-03-04 15:53 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +            if path is not None
done

2024-03-04 16:10 UTC, kmilo9999 commented
@hollandjg @cpaniaguam Unintentionally, that I dismissed your last approved reviews. Can you give a quick approval ?

2024-03-04 17:10 UTC, cpaniaguam requested changes
With refreshed eyes, I added a couple more easy cleanups that I missed last time!

2024-03-04 17:10 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
>                      tt = tt[:-1]
I just noticed this can be simplified to:
```suggestion
                if not nopower:
                    tt = tt[:-1]
```

2024-03-04 17:10 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
>                  tt = tt[:-1]
And this one:
```suggestion
            if not nopower:
                tt = tt[:-1]
```

2024-03-04 17:10 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
>                  tt = tt[:-1]
```suggestion
            if not nopower:
                tt = tt[:-1]
```

2024-03-04 18:18 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
>                  tt = tt[:-1]
Done

2024-03-04 18:18 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
>                  tt = tt[:-1]
Done

2024-03-04 18:18 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        fig_size = [10, 4] if fig_size else fig_size
Done

2024-03-04 18:18 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        fig_size = [10, 4] if fig_size else fig_size
removed `fig_size `initialization

2024-03-04 18:18 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +def set_timeaxis_days(ax, int1=1, int2=2, bymonthday=range(1, 32)):
Removed line 817

2024-03-04 18:35 UTC, hollandjg commented on src/icesat2_tracks/local_modules/JONSWAP_gamma.py
> +    return alpha * g**2.0 * w ** (-5.0) * np.exp(-5.0 / 4.0 * (w / wp) ** -4)
```suggestion
    # Hz**-5 m**2 /s**4 = m**2 sec
    return alpha * g**2.0 * w ** (-5.0) * np.exp(-5.0 / 4.0 * (w / wp) ** -4)
```

2024-03-04 18:39 UTC, hollandjg submitted a review, later dismissed
Great!

2024-03-07 19:02 UTC, cpaniaguam requested changes
A couple more simple changes. Some are from the previous review that I unresolved.

2024-03-07 19:02 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +        f.append(open(h, "r").read())
```suggestion
        with open(h, "r") as file:
            f.append(file.read())
```

2024-03-07 19:23 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        print("arrays have not the same shape")
This seems like a larger logical change – it's certainly shorter and uses new tools, but perhaps this PR isn't the right place?

2024-03-07 19:42 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
>      if plot == True:
Done

2024-03-07 19:42 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
I reformatted it

2024-03-07 19:43 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        print("arrays have not the same shape")
I added it to this PR. It is a small change we can apply.

2024-03-07 19:44 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
>      if plot == True:
Done

2024-03-07 19:44 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +            )  # , vmin=self.ctrs_min)
Done

2024-03-07 19:44 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        ax.set_yticklabels(" " + str(y) + " s" for y in self.ylabels)
Done

2024-03-07 19:44 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +            ax = ax
removed

2024-03-07 19:45 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +                    tt = tt[:-1]
This change is already in the current branch https://github.com/brown-ccv/icesat2-tracks/blob/clean-files-modules/src/icesat2_tracks/local_modules/m_general_ph3.py#L618

2024-03-07 21:07 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +def set_timeaxis_days(ax, int1=1, int2=2, bymonthday=range(1, 32)):
This change is already applied it to the current branch

2024-03-07 21:08 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/JONSWAP_gamma.py
> +    return alpha * g**2.0 * w ** (-5.0) * np.exp(-5.0 / 4.0 * (w / wp) ** -4)
This change is already applied in the current branch

2024-03-07 21:34 UTC, hollandjg approved these changes
Looks good to me!

2024-03-07 21:34 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +            print("arrays have not the same shape")
We should update the pyproject.toml file to say that the code is only compatible with python 3.10 and up – this will break under 3.9 (which we had listed before as being compatible). Perhaps we can add that to the renaming the package PR.

2024-03-08 16:52 UTC, cpaniaguam requested changes
I added some more comments and suggestions.

In case you are not aware, for explicit PR suggestions (I also added suggestions that GitHub can't handle because they include deleted lines) you can use GitHub's feature to batch commit PR review suggestions. Here is how:

1. Navigate to the "Files changed" tab in the pull request.
2. In a suggestion, use the "Add suggestion to batch" button to queue up changes you'd like to make.
3. Once you've added all the changes you want, click on the "Commit suggestions" button near the top of the window. This will open a dialog box where a commit message can be added.
4. After adding the commit message, click on the "Commit changes" button. This will apply all the queued up changes in one commit.

An added benefit of batch commiting suggestions from a PR review is that the commit will be co-authored by both the reviewer and the reviewee. This is beneficial as it gives credit to both parties for their contributions to the code change. It's a great way to acknowledge the collaborative effort involved in improving the codebase. Thanks @kmilo9999 :)

2024-03-08 16:52 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
>          for k in self.mom.keys():
For the for loop L275-289
```python
        for k in self.mom.keys():
            stack = np.empty([nbin, self.f.size])
            for i, mom in enumerate(self.mom_list):
                stack[i, :] = mom[k]  # stack them
            
            # mean them and decide prewhitening
            if prewhite is None:
                factor = 1
            elif prewhite == 1:
                factor = 2 * np.pi * self.f
            elif prewhite == 2:
                factor = (2 * np.pi * self.f) ** 2
        
            self.moments_stack[k] = stack * factor
            self.moments_est[k] = np.nanmean(stack, axis=0) * factor
```

2024-03-08 16:52 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +        mom["P23"] = (X[1, 1:] * X[2, 1:].conj()).real
```python
        def conj_operation(x, y, key):
            return (x * y.conj()).real if key.startswith("P") else (x * y.conj()).imag

        keys = ["P11", "P22", "P33", "Q12", "Q13", "Q23", "P13", "P12", "P23"]
        index_pairs = [
            (0, 0),
            (1, 1),
            (2, 2),
            (0, 1),
            (0, 2),
            (1, 2),
            (0, 2),
            (0, 1),
            (1, 2),
        ]

        mom = {
            key: conj_operation(X[i, 1:], X[j, 1:], key)
            for key, (i, j) in zip(keys, index_pairs)
        }

2024-03-08 16:52 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +        N_sel[k] = moments_est[k][freq_sel_bool]
```suggestion
    N_sel = {k: v[freq_sel_bool] for k, v in moments_est.items()}
```

2024-03-08 16:52 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> -    # Lygre and Krongstad 1986 have here sqrt(N_sel['P11'] *(N_sel['P22'] + N_sel['P33']). I guess its a typo.
This comment seems useful.

2024-03-08 16:52 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
>      f.close()
```suggestion
    with open(outfile, "wb") as f:
        pickle.dump(data, f, pickle.HIGHEST_PROTOCOL)
    print("saved to:", outfile)

```

2024-03-08 18:56 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +        mom["P23"] = (X[1, 1:] * X[2, 1:].conj()).real
I'd recommend against doing this change. You're at risk of getting out of sync between the keys and the index pairs.

2024-03-08 19:22 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +        mom["P23"] = (X[1, 1:] * X[2, 1:].conj()).real
@hollandjg No issues with correctness there, but a lot of repetition. I had maintainability in mind. Perhaps something like this is more your style:
```python
        mom = {
            "P11": (X[0, 1:] * X[0, 1:].conj()).real,
            "P22": (X[1, 1:] * X[1, 1:].conj()).real,
            "P33": (X[2, 1:] * X[2, 1:].conj()).real,
            "Q12": (X[0, 1:] * X[1, 1:].conj()).imag,
            "Q13": (X[0, 1:] * X[2, 1:].conj()).imag,
            "Q23": (X[1, 1:] * X[2, 1:].conj()).imag,
            "P13": (X[0, 1:] * X[2, 1:].conj()).real,
            "P12": (X[0, 1:] * X[1, 1:].conj()).real,
            "P23": (X[1, 1:] * X[2, 1:].conj()).real,
        }
```

Still quite a bit of repeated code but not as much as the original.

2024-03-08 21:34 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +        mom["P23"] = (X[1, 1:] * X[2, 1:].conj()).real
I think I'd go for something like this if I wanted to use a dictionary comprehension:
```python
d = {
    "P11": (0, 0, "real"),
    "P22": (1, 1, "real"),
    ...
}
```
just to make sure the keys didn't get off-by-one from the values which can occur with `zip` (which doesn't throw an error if your iterables are of different length).

But I'm not sure where the balance point falls in terms of maintainability here – 
- the original is readable shortish and readable (10 lines, but really it's only 2 with varying indices) but if you have to change it there's a risk you'll make a mistake if you miss one, which is one of the problems that DRY tries to solve. 
- The proposal using the key name to steer whether you're taking the real or imaginary part seems a bit brittle, but I don't understand the meaning of the keys and maybe it's sensible in the context. 
- This looks like a matrix multiplication – perhaps just working out what the numpy command is which multiplies these matrices in the right way (from a semantic point of view) would be even better.

2024-03-10 21:31 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +    d2 = N_sel["Q13"] / np.sqrt(N_sel["P11"] * (N_sel["P22"] + N_sel["P33"]))
```suggestion
    d2 = N_sel["Q13"] / np.sqrt(N_sel["P11"] * (N_sel["P22"] + N_sel["P33"]))
    # Lygre and Krongstad 1986 have here sqrt(N_sel['P11'] *(N_sel['P22'] + N_sel['P33']). I guess its a typo.
```

2024-03-11 13:53 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
Renamed all classes using PEP8

2024-03-11 16:25 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +            print("save with: ", name)
#192

2024-03-12 18:31 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        self.length = -self.span[0] + self.span[1]
The change has been applied

2024-03-12 19:15 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
>      store.close()
Done

2024-03-12 19:15 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
Done

2024-03-12 19:17 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        self.data_unit = data_unit if data_unit is not None else "X"
Changed

2024-03-12 19:17 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +                # error_Ey[k,:]=Ey
Removed

2024-03-12 19:20 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +    h5f = h5py.File(path + name + ".h5", "r")
Done

2024-03-12 19:22 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
>      store.close()
Done

2024-03-12 19:24 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +        message = "\n ".ljust(2) + " " + string
Done

2024-03-12 19:24 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +        print(hist + message)
Done

2024-03-12 19:26 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +        print(hist + message)
Done

2024-03-12 19:26 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +        stringg = stringg + "\n " + name.ljust(5) + str(I)
Done

2024-03-12 19:28 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +        message = "\n ".ljust(5) + " " + stringg
Done

2024-03-12 19:29 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +        self.f = self.df * np.arange((self.n - 1) / 2.0 + 1)
Done

2024-03-12 19:30 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +    T["dt64"] = time_as_datetime64
Done

2024-03-12 19:30 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +                print("stoped by max#")
Done

2024-03-12 19:31 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +    T["dt64"] = time_as_datetime64
Done

2024-03-12 20:01 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +                print("stoped by max#")
Done

2024-03-12 20:04 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> -    # Lygre and Krongstad 1986 have here sqrt(N_sel['P11'] *(N_sel['P22'] + N_sel['P33']). I guess its a typo.
Done

2024-03-12 20:55 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +        mom["P23"] = (X[1, 1:] * X[2, 1:].conj()).real
#193

2024-03-12 20:55 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
>      store.close()
Done

2024-03-12 20:55 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +        stringg = stringg + "\n " + name.ljust(5) + str(I)
Done

2024-03-12 20:56 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +    ticklabels = [" " for i in range(len(b))]
Done

2024-03-12 20:56 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +        print("saved at: " + full_name)
Removed second function

2024-03-12 20:58 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +        raise Warning("no propper case")
#194

2024-03-12 20:59 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
>      pass
#195

2024-03-12 21:00 UTC, kmilo9999 commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +                    print("length of TS " + str(data.size))
#196

2024-03-12 21:01 UTC, kmilo9999 commented
@cpaniaguam I finished your last review. Check it again and let me know if I there anything I missed

2024-03-12 22:15 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +                    print("length of TS " + str(data.size))
This is resolved in #179 – I've marked the issue as being resolved there too.

2024-03-13 14:38 UTC, cpaniaguam requested changes
Just a couple more easy changes.

2024-03-13 14:38 UTC, cpaniaguam commented on src/icesat2waves/local_modules/m_general_ph3.py
> +    STR["right_limit"] = line_right
```suggestion
    STR = {
        "t_pos": [],
        "index": index,
        "amp": [],
        "freq": [],
        "out": [],
        "amp_shape": [],
        "left_limit": line_left,
        "right_limit": line_right,
    }
```

2024-03-13 14:38 UTC, cpaniaguam commented on src/icesat2waves/local_modules/m_spectrum_ph3.py
> +        MEM["unit_dir"] = self.moments_unit + "/deg/Hz"
```suggestion
        MEM = {}
        MEM["D"], MEM["S"], MEM["E"], MEM["freq"], MEM["theta"] = MEM_cal(
            self.moments_est, self.f, theta=theta, flim=flim
        )
        MEM.update(
            {
                "fmin": flim[0],
                "fmax": flim[1],
                "unit_power": self.moments_unit + "/Hz",
                "unit_dir": self.moments_unit + "/deg/Hz",
            }
        )
```

2024-03-13 14:38 UTC, cpaniaguam commented on src/icesat2waves/local_modules/m_spectrum_ph3.py
> +        MEM["unit_dir"] = self.moments_unit + "/deg/Hz"
```suggestion
        MEM = {}
        MEM["D"], MEM["S"], MEM["E"], MEM["freq"], MEM["theta"] = MEM_cal(
            self.moments_est, self.f, theta=theta, flim=flim
        )
        MEM.update(
            {
                "fmin": flim[0],
                "fmax": flim[1],
                "unit_power": self.moments_unit + "/Hz",
                "unit_dir": self.moments_unit + "/deg/Hz",
            }
        )
```

2024-03-13 15:55 UTC, kmilo9999 commented on src/icesat2waves/local_modules/jonswap_gamma.py
> -    )  # units of m^2 / Hz
comment added

2024-03-13 15:57 UTC, kmilo9999 commented on src/icesat2waves/local_modules/m_general_ph3.py
> +        viewscale = view_scale if view_scale is not None else 0.5
removed

2024-03-13 15:57 UTC, kmilo9999 commented on src/icesat2waves/local_modules/m_general_ph3.py
> +        fig_scale=None,
Changed

2024-03-13 15:57 UTC, kmilo9999 commented on src/icesat2waves/local_modules/m_general_ph3.py
> +        fig_scale = fig_scale if fig_scale is not None else 1
removed

2024-03-13 15:58 UTC, kmilo9999 commented
@cpaniaguam Done! Check again.

2024-03-13 17:39 UTC, cpaniaguam approved these changes
Looks good!

I am not really sure why most of the conversations disappeared. They didn't appear in context so I had to have two windows opened, one at the conversations page and another with the file being reviewed. Also, in the future please consider using the `add suggestion to batch` feature to co-author commits.

2024-03-13 17:46 UTC, kmilo9999 commented
I did use the `suggestion to batch` feature in the last 2 review following your advice

2024-03-13 17:46 UTC, kmilo9999 commented
@hollandjg everything good on your side?

2024-03-13 17:58 UTC, hollandjg approved these changes
Looks good to me! 🚀

2024-03-13 18:00 UTC, merged