feat: add logger configuration and upate logging in step 1
brown-ccv/icesat2waves pull request #138
Opened 2024-02-29 15:42 UTC by hollandjg

2024-02-29 22:00 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +
```suggestion
```

2024-03-01 20:05 UTC, cpaniaguam commented on src/icesat2_tracks/app.py
The description says the default behavior is to hide all the output. Is this documented somewhere in app itself? This is what's currently displayed in the help for the app.
```shell
$ icesat2waves --help
Usage: app.py [OPTIONS] COMMAND [ARGS]...

  Analyze data from the ICESAT2 satellite.

Options:
  --verbose / --no-verbose  [default: no-verbose]
  --debug / --no-debug      [default: no-debug]
  --help                    Show this message and exit.

Commands:
  correct-separate
  define-angle               TODO: add docstring
  load-file                  Open an ICEsat2 tbeam_stats.pyrack, apply...
  make-b04-angle             TODO: add docstring
  make-iowaga-threads-prior  TODO: add docstring
  make-spectra               TODO: add docstring
  plot-spectra               TODO: add docstring
  separate-var               TODO: add docstring
```
Note that `no-verbose` and `no-debug` are both defaults. It's difficult for me to decide what that means. I guess no logging option would be set up. But, what are the consequences of that?

I think it'd be good to document the default behavior in the help, and set up one and only one default option in case no option is provided. To these ends, the docstring in the call back function could be leveraged. To gain more control over the options -- and document them -- the `typer.Option` function can be used as shown below. I think having a single option (`mode`, say) that takes one of two possible values (`verbose` or `debug`) is sensible for this use case. Finally, it's probably a good idea to set the value of `invoke_without_command` to `True` in the `app.callback` decorator to set up the logging level appropriately even if a subcommand is provided.

```python
def set_log_level(value: str):
    if value == "verbose":
        logging.basicConfig(level=logging.INFO)
    elif value == "debug":
        logging.basicConfig(level=logging.DEBUG)
    else:
        raise typer.BadParameter("Invalid mode. Valid options are 'verbose' or 'debug'.")


@app.callback(invoke_without_command=True)
def main(
    mode: str = typer.Option("verbose", "--mode", help="Set the log level. Options are 'verbose' or 'debug'.")
):
    """Analyze data from the ICESAT2 satellite. Document its behavior here."""
    set_log_level(mode)
```

With these additions the `--help` page would look like this:
```shell
$ icesat2waves --help
Usage: app.py [OPTIONS] COMMAND [ARGS]...

  Analyze data from the ICESAT2 satellite. Document its behavior here.

Options:
  --mode TEXT  Set the log level. Options are 'verbose' or 'debug'.  [default:
               verbose]
  --help       Show this message and exit.

Commands:
  correct-separate
  define-angle               TODO: add docstring
  load-file                  Open an ICEsat2 tbeam_stats.pyrack, apply...
  make-b04-angle             TODO: add docstring
  make-iowaga-threads-prior  TODO: add docstring
  make-spectra               TODO: add docstring
  plot-spectra               TODO: add docstring
  separate-var               TODO: add docstring

2024-03-04 16:28 UTC, hollandjg commented on src/icesat2_tracks/app.py
Thanks for the feedback here! I've made some modifications so that the CLI is like this:
```
% icesat2waves --help                                                                                                                                                                                                                    
Usage: icesat2waves [OPTIONS] COMMAND [ARGS]...

  Analyze data from the ICESAT2 satellite.

Options:
  --log [quiet|warning|verbose|debug]
                                  Set the log level  [default: warning]
  --help                          Show this message and exit.

Commands:
  correct-separate
  define-angle               TODO: add docstring
  load-file                  Open an ICEsat2 tbeam_stats.pyrack, apply...
  make-b04-angle             TODO: add docstring
  make-iowaga-threads-prior  TODO: add docstring
  make-spectra               TODO: add docstring
  plot-spectra               TODO: add docstring
  separate-var               TODO: add docstring
```

2024-03-04 16:30 UTC, hollandjg commented on src/icesat2_tracks/app.py
I tried out the `invoke_without_command=True`, but it removes the warning and help message if you run `icesat2waves` without any arguments.
(with `invoke_without_command=True`:
```
% icesat2waves
%
```
without:
```
% icesat2waves
Usage: icesat2waves [OPTIONS] COMMAND [ARGS]...
Try 'icesat2waves --help' for help.

Error: Missing command.
```)

We don't need the logger to be configured if there isn't a command – it should just show the warning and exit, and nothing should get logged. If something throws a logging message before we've set up the configuration, then the code will run the `basicConfig` with default parameters. That seems fine to me.

2024-03-04 20:33 UTC, cpaniaguam commented on src/icesat2_tracks/app.py
> +    logging.basicConfig(level=level)
I like the flexibility of this design. What do you think about embedding the mapping as a property of the enum and use the level directly in `logging.basicConfig`?
```suggestion
class _LogLevel(str, Enum):
    QUIET = "quiet"
    WARNING = "warning"
    VERBOSE = "verbose"
    DEBUG = "debug"

    @property
    def level(self):
        return {
            _LogLevel.QUIET: logging.CRITICAL,
            _LogLevel.WARNING: logging.WARNING,
            _LogLevel.VERBOSE: logging.INFO,
            _LogLevel.DEBUG: logging.DEBUG,
        }[self.value]
 
       
@app.callback()
def main(
    log: Annotated[
        _LogLevel,
        Option(help="Set the log level"),
    ] = "warning"
):
    """Analyze data from the ICESAT2 satellite."""
    logging.basicConfig(level=log.level)
```

This avoids using the dict as a global in `main`.

2024-03-04 20:56 UTC, hollandjg commented on src/icesat2_tracks/app.py
> +    logging.basicConfig(level=level)
Nice! Let's do that.

2024-03-05 18:36 UTC, kmilo9999 requested changes
My only question here. Is all the log output going to std error? There are some std output we can do as a feedback to the user on what is happening. For example that the operation finished, or  file was saved.

2024-03-05 18:36 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +    _logger.info("STARTS")
This can be remove. That is one of my debug lines of code.

2024-03-05 18:36 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +    _logger.info("ENDS")
This can be remove. That is one of my debug lines of code.

2024-03-05 18:36 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +    ATL03_track_name = "ATL03_" + track_name + ".h5"
```suggestion
    ATL03_track_name = f"ATL03_{track_name}.h5"
```

2024-03-05 18:36 UTC, kmilo9999 commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +    DD["tracks"]["ATL03"] = "ATL10-" + track_name
```suggestion
    DD["tracks"]["ATL03"] = f"ATL10-{track_name}"
```

2024-03-05 19:32 UTC, cpaniaguam requested changes
Some quick suggested improvements here.

2024-03-05 19:32 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +    _logger.info("STARTS")
I think this one is useful though!

2024-03-05 19:32 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +    _logger.info("ENDS")
I like this one too!

2024-03-05 19:32 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_colormanager_ph3.py
> +        _logger.debug(i['name'] + '  ' + str(i['data']['values']))
```suggestion
        _logger.debug("swatch name: %s, swatch values: %s", i['name'], i['data']['values'])
```

2024-03-05 19:32 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_colormanager_ph3.py
> +    _logger.debug(f'save at: {full_name}')
```suggestion
    _logger.debug('save at %s: full_name')
```

2024-03-05 19:32 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_colormanager_ph3.py
> +    _logger.debug('loaded from: {full_name}')
```suggestion
    _logger.debug('loaded from: %s' full_name)
```

2024-03-05 19:32 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_colormanager_ph3.py
> +                _logger.debug('color theme: '+name)
```suggestion
                _logger.debug("color theme: %s", name)
```

2024-03-05 19:32 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_colormanager_ph3.py
> +                    _logger.debug(path+'mhell_colortheme17')
```suggestion
                    _logger.debug("path: %s", path+'mhell_colortheme17'))
```

2024-03-05 19:32 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_colormanager_ph3.py
> +                _logger.debug('  '+key)
```suggestion
                _logger.debug("   %s", key)
```

2024-03-05 19:32 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_colormanager_ph3.py
> +            _logger.debug('  rels dict:')
```suggestion
            _logger.debug('  rels dict keys:')
```

2024-03-05 19:41 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +    _logger.info("STARTS")
```suggestion
```

2024-03-05 19:41 UTC, hollandjg commented on src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py
> +    _logger.info("ENDS")
```suggestion
    _logger.info("Finished fetching ATL03 data from sliderule")
```

2024-03-05 19:43 UTC, hollandjg commented
> There are some std output we can do as a feedback to the user on what is happening. For example that the operation finished, or file was saved.

We can totally do that, but I'd do that in a separate PR – this set is large enough and I want to minimize the merge conflicts. But adding an info at the start and the end of each main function in the analysis directory would be neat.

2024-03-05 19:45 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_colormanager_ph3.py
> +                    _logger.debug("path: %s", path+'mhell_colortheme17'))
```suggestion
                    _logger.debug("path: %s", path+'mhell_colortheme17')
```

2024-03-05 20:09 UTC, cpaniaguam submitted a review, later dismissed
👍

2024-03-06 15:40 UTC, kmilo9999 approved these changes
Looks good

2024-03-14 15:16 UTC, cpaniaguam requested changes
Thanks for your contributions to this project, John!

I pointed out some files that are not uniformly formatted and a class that is not named according to PEP8 -- I guess it slipped through the cracks.

2024-03-14 15:16 UTC, cpaniaguam commented on src/icesat2waves/local_modules/m_colormanager_ph3.py
This file does not seem to be uniformly formatted. Also, the `color` class is not named according to PEP8.

2024-03-14 16:52 UTC, hollandjg commented on src/icesat2waves/local_modules/m_colormanager_ph3.py
I've reformatted everything in a follow-on PR #198 – I don't want to deal with the merge conflicts or increase the number of changes here. 

The `color` class is not named according to PEP8 is true. Not in scope for this PR – I'll open an issue.

2024-03-14 16:52 UTC, hollandjg commented on src/icesat2waves/local_modules/m_colormanager_ph3.py
New issue:
- #199

2024-03-14 19:16 UTC, cpaniaguam approved these changes

2024-03-18 13:56 UTC, kmilo9999 approved these changes
Looks good to me

2024-03-18 19:40 UTC, merged