chore: logging 2 – replace print in analysis\_db files
brown-ccv/icesat2waves pull request #176
Opened 2024-03-04 23:15 UTC by hollandjg

2024-03-05 19:10 UTC, cpaniaguam requested changes
A few suggestions here.

2024-03-05 19:10 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B04_angle.py
> +        _logger.critical("exit()")
```suggestion
        _logger.critical("terminating..)")
```

2024-03-05 19:10 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B04_angle.py
> +        _logger.debug(gi)
```suggestion
        _logger.debug("gi = %s", gi)
```

2024-03-05 19:10 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B04_angle.py
> +        _logger.info("done with %s %s", group, xi / 1e3)
```suggestion
        _logger.info("done with group %s,  xi = %s", group, xi / 1e3)
```

2024-03-05 19:10 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B04_angle.py
> +        _logger.warning(f"This is a warning: %s", e)
```suggestion
        _logger.warning("This is a warning: %s", e)
```

2024-03-05 19:10 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
> +        _logger.info("%s %s", str(self.min), str(self.max))
```suggestion
        _logger.info("min %s, max %s", self.min, self.max)
```

2024-03-05 19:10 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B05_define_angle.py
> +        _logger.critical("exit()")
```suggestion
        _logger.critical("exiting")
```

2024-03-05 19:10 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        _logger.debug("%s", alpah_v2_sub.argmin())
```suggestion
        _logger.debug("alpah_v2_sub: %s", alpah_v2_sub)
        _logger.debug("alpah_v2_sub.argmin: %s", alpah_v2_sub.argmin())
```

2024-03-05 19:10 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        )
```suggestion
        _logger.debug(
            "n_breakpoints %s\n%s", n_breakpoints, pw_fit.get_results()["converged"]
        )
```

2024-03-05 19:10 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +    _logger.debug("%s", x)
```suggestion
    _logger.debug("From calculate_k_end -- x: %s", x)
```

2024-03-05 19:10 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +        _logger.debug("%s", bb)
```suggestion
        _logger.debug("bb: %s", bb)
```

2024-03-05 19:10 UTC, cpaniaguam commented on src/icesat2_tracks/analysis_db/B06_correct_separate_var.py
> +    _logger.info("done. saved target at %s../B06_success", str(plot_path))
```suggestion
    _logger.info("done. saved target at %s../B06_success", plot_path)
```

2024-03-05 21:57 UTC, cpaniaguam approved these changes
👍

2024-03-18 14:07 UTC, kmilo9999 commented on src/icesat2waves/analysis_db/B06_correct_separate_var.py
> +    _logger.debug("--------------------------")
It's this print important ?

2024-03-18 14:08 UTC, kmilo9999 submitted a review, later dismissed
Looks good

2024-03-19 23:21 UTC, cpaniaguam approved these changes

2024-03-20 17:03 UTC, merged