chore: logging 3 - remove prints from tools directory
brown-ccv/icesat2waves pull request #177
Opened 2024-03-04 23:21 UTC by hollandjg

2024-03-05 18:54 UTC, cpaniaguam requested changes
Some suggested cleanups here.

2024-03-05 18:54 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/angle_optimizer.py
> +            _logger.debug("%s", self.LM.report_fit(self.fitter_optimize))
```suggestion
            _logger.debug("fit report: %s", self.LM.report_fit(self.fitter_optimize))
```

2024-03-05 18:54 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/filter_regrid.py
> +            _logger.debug(i)
```suggestion
            _logger.debug("i= %s", i)
```

2024-03-05 18:54 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/generalized_FT.py
> +                _logger.debug("%s %s", prior[0][0:3], prior[1][0:3])
```suggestion
                _logger.debug("2nd step: use set priors of types: %s %s", type(prior[0]), type(prior[1]))
                _logger.debug("first three elements of priors: %s %s", prior[0][0:3], prior[1][0:3])
```

2024-03-05 18:54 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/iotools.py
> +    _logger.debug("%s %s %s",ID_name, batch_key, ID_flag)
```suggestion
    _logger.debug("id name: %s, batch key: %s, id flag: %s", ID_name, batch_key, ID_flag)
```

2024-03-05 18:54 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/iotools.py
> +        _logger.debug(colnames)
```suggestion
        _logger.debug("colnames: %s", colnames)
```

2024-03-05 18:54 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/iotools.py
> +            _logger.debug(colerror)
```suggestion
            _logger.debug("colerror: %s", colerror)
```

2024-03-05 18:54 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +                    _logger.debug('length of TS %s ms', str(dsize))
```suggestion
                    _logger.debug('end of TS is reached')
                    _logger.debug('last spec No: %s', last_k)
                    _logger.debug('spec container: %s', specs.shape)
                    _logger.debug('last used Timestep: %s', last_used_TS)
                    _logger.debug('length of TS %s ms', dsize)
```

2024-03-05 18:54 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spicke_remover.py
> +                              str( np.nanmax(np.abs(data))))
```suggestion
                _logger.debug('true: %s < %s',
                              nstd* datastd,
                              np.nanmax(np.abs(data)))
```

2024-03-05 18:54 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spicke_remover.py
> +                              str( np.nanmax(np.abs(data))))
```suggestion
                _logger.debug('False: %s > %s ',
                              nstd* datastd,
                              np.nanmax(np.abs(data)))
```

2024-03-05 21:52 UTC, cpaniaguam requested changes
One more change here.

2024-03-05 21:52 UTC, cpaniaguam commented on src/icesat2_tracks/ICEsat2_SI_tools/spectral_estimates.py
> +        _logger.debug(map_func)
I am not sure this one is useful.
```suggestion
```

2024-03-05 23:04 UTC, cpaniaguam submitted a review, later dismissed
All good!

2024-03-18 14:08 UTC, kmilo9999 submitted a review, later dismissed

2024-03-20 20:02 UTC, hollandjg commented on src/icesat2waves/tools/iotools.py
> +    _logger.debug("download to: %s", dpath + "/" + HOST[-1])
Wow, that works? It looks like a syntax error to me. I didn't know you could concatenate strings that way. How does Black reformat it? I'm not super keen – I don't think the suggestion makes the syntax any clearer.

2024-03-20 20:34 UTC, cpaniaguam commented on src/icesat2waves/tools/iotools.py
> +    _logger.debug("download to: %s", dpath + "/" + HOST[-1])
Maybe it doesn't work. I guess it only works with literals.

2024-03-21 14:58 UTC, merged