chore: logging 4 – remove prints from config directory
brown-ccv/icesat2waves pull request #178
Opened 2024-03-04 23:26 UTC by hollandjg

2024-03-05 18:40 UTC, cpaniaguam requested changes
This one was easy, thanks! Just one change here.

2024-03-05 18:40 UTC, cpaniaguam commented on src/icesat2_tracks/config/generate_colors.py
> +    _logger.debug("%s %s", i['name'], str(i['data']['values']))
```suggestion
    _logger.debug("swatch name: %s, values: %s", i['name'], i['data']['values'])
```

2024-03-05 21:45 UTC, cpaniaguam submitted a review, later dismissed
👍

2024-03-22 13:37 UTC, kmilo9999 approved these changes
Looks good

2024-03-22 14:11 UTC, merged