chore: logging 5 - remove prints from local_modules directory
brown-ccv/icesat2waves pull request #179
Opened 2024-03-04 23:26 UTC by hollandjg

2024-03-05 18:34 UTC, cpaniaguam requested changes
Thanks for your contributions, John! I pointed some issues with updates to commented lines that seem to have been changed programmatically. What to do with them? If they are kept and used later, extra work would be needed to make the messages lazily evaluated. I also noted a number of specific opportunities for improvement.

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +    if verbose: _logger.debug(stats)
```suggestion
    if verbose: _logger.debug("stats: %s", stats)
```

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +            _logger.debug(span)
```suggestion
            _logger.debug("span: %s", span)
```

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +            _logger.debug(iindex)
```suggestion
            _logger.debug("iindex: %s", iindex)
```

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +                        _logger.debug('right postion: %s',i+span[1])
Will these get hit when following a return statement?

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        _logger.debug('type is numpy.datetime64', time_lin.shape)
```suggestion
        _logger.debug('type is numpy.datetime64 with shape: %s', time_lin.shape)
```

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        _logger.debug('ERROR: shapes are not correct')
Use a higher logging level here? Though an error is not thrown afterwards idk.
```suggestion
        _logger.error('ERROR: shapes are not correct')
```

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        _logger.debug("%s %s %s", f.shape, time_lin.shape, data.shape)
Add context here?

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +            _logger.debug("%s %s", line_right[-1] ,time_lin[-1])
Some of these could benefit from some context.

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +    _logger.debug("%s %s", RAMS_slope, RAMS_intercept)
Add context?

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_general_ph3.py
Like the previous files, these seem to have been changed programmatically. Some are commented and other could use more expressive messages. I suggested a few additions.

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +                    _logger.debug('length of TS '+ str(dsize) +'ms')
```suggestion
                    _logger.debug("end of TS is reached")
                    _logger.debug("last spec No: %s", last_k)
                    _logger.debug("spec container shape: %s", specs.shape)
                    _logger.debug("last used Timestep: %s", last_used_TS)
                    _logger.debug("length of TS: %s ms", dsize)
```

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +        _logger.debug('mean variance of timeseries chunks: ',self.chunks.var(axis=1).mean() if self.save_chunks is True else 'data not saved')
```suggestion
        _logger.debug("variance of unweighted timeseries: %s", self.data.var())
        _logger.debug("mean variance of timeseries chunks: %s", self.chunks.var(axis=1).mean() if self.save_chunks is True else 'data not saved')
```

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +        _logger.debug('variance of the pwelch Spectrum: ',self.var)
```suggestion
        _logger.debug('variance of the pwelch Spectrum: %s', self.var)
```

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +        _logger.debug("%s", data_size_adjust)
```suggestion
        _logger.debug("data size adjust: %s", data_size_adjust)
```

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +        _logger.debug("%s", self.hist)
```suggestion
        _logger.debug(".hist variable: %s", self.hist)
```

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +        _logger.debug("%s %s", self.f.size,self.time.size)
```suggestion
        _logger.debug("data power mean shape: %s", self.data_power_mean.shape)
        _logger.debug("f size: %s, time size: %s", self.f.size, self.time.size)
```

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +        _logger.debug("%s", P.meta)
```suggestion
        _logger.debug("P.meta: %s", P.meta)
```

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +        _logger.debug("%s", h5f.keys())
```suggestion
        _logger.debug("%s h5f keys: %s", name, h5f.keys())
```

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +        _logger.debug(hist+message)
```suggestion
        _logger.debug("hist message %s", hist+message)
```

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +        _logger.debug(hist+message)
```suggestion
        _logger.debug("hist message %s", hist+message)
```

2024-03-05 18:34 UTC, cpaniaguam commented on src/icesat2_tracks/local_modules/m_tools_ph3.py
> +		_logger.debug(i.shape)
```suggestion
		_logger.debug("shape of %s: %s", i, i.shape)
```

2024-03-05 20:48 UTC, hollandjg commented
> If they are kept and used later, extra work would be needed to make the messages lazily evaluated. 

I agree. A lot of these lines are also touched in #131 (and a lot will be removed), so I don't want to make all the corrections just yet. Once we see what the final merge looks like we can revisit here.

I'm also mindful of the extra effort going through and fixing commented out code might add, and I feel like we're close to the point of diminishing returns here. (There's a strong argument that we hit that point two weeks ago when you said this would be too much work – it's been more work than I expected.)

2024-03-06 15:35 UTC, kmilo9999 approved these changes
Looks good to me

2024-03-13 21:58 UTC, hollandjg commented on src/icesat2_tracks/local_modules/JONSWAP_gamma.py
> +    # _logger.debug(dloc)
These should be resolved now.

2024-03-13 21:58 UTC, hollandjg commented on src/icesat2_tracks/local_modules/JONSWAP_gamma.py
> +    # _logger.debug('nu='+str(wp*U/(g)))
These should all be resolved now.

2024-03-13 22:00 UTC, hollandjg commented on src/icesat2_tracks/local_modules/JONSWAP_gamma.py
> +    _logger.debug(Jm)
Would review any context in another PR, if we have more budget.

2024-03-13 22:09 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +            _logger.debug(span)
Done

2024-03-13 22:09 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +                        _logger.debug('right postion: %s',i+span[1])
No, but the return statement itself won't be reached because the raise happens before it.

2024-03-13 22:10 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +                        _logger.debug('right postion: %s',i+span[1])
This code needs refactoring, probably.

2024-03-13 22:10 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +            _logger.debug(iindex)
Done

2024-03-13 22:10 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +    if verbose: _logger.debug(stats)
Done

2024-03-13 22:10 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +                _logger.debug("%s > %s", high, var[-1])
Done

2024-03-13 22:10 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        _logger.debug(timestamp)
Done

2024-03-13 22:10 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +    _logger.debug(G.keys())
Done

2024-03-13 22:11 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
>              for key in self.__dict__.keys():
Done

2024-03-13 22:11 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +                _logger.debug(key)
Done

2024-03-13 22:11 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +                _logger.debug("%s", self.clevs)
Done

2024-03-13 22:11 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +                _logger.debug("%s", self.clevs)
Done

2024-03-13 22:11 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +                _logger.debug(str(self.min), str(self.max) )
Done

2024-03-13 22:11 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +                _logger.debug("%s %s", tt[:-1].shape, self.fs[:].shape,dd.T.shape)
Done

2024-03-13 22:12 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        _logger.debug('type is numpy.datetime64', time_lin.shape)
Done

2024-03-13 22:12 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        _logger.debug("%s %s %s", f.shape, time_lin.shape, data.shape)
Done

2024-03-13 22:13 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +        _logger.debug('ERROR: shapes are not correct')
Done

2024-03-13 22:14 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +            _logger.debug("%s %s", line_right[-1] ,time_lin[-1])
Done

2024-03-13 22:14 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +    _logger.debug("%s %s", RAMS_slope, RAMS_intercept)
Done

2024-03-13 22:15 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +                    _logger.debug('length of TS '+ str(dsize) +'ms')
Done

2024-03-13 22:16 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +        _logger.debug('variance of the pwelch Spectrum: ',self.var)
Done

2024-03-13 22:16 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +        _logger.debug("%s", data_size_adjust)
Done

2024-03-13 22:17 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +        _logger.debug("%s", self.hist)
Done

2024-03-13 22:17 UTC, hollandjg commented on src/icesat2_tracks/local_modules/JONSWAP_gamma.py
> +    # _logger.debug('nu='+str(wp*U/(g)))
Done

2024-03-13 22:18 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_colormanager_ph3.py
> +        _logger.debug("%s %s", i['name'], i['data']['values'])
Done

2024-03-13 22:19 UTC, hollandjg commented on src/icesat2_tracks/local_modules/JONSWAP_gamma.py
> +    # _logger.debug(tt)
Done

2024-03-13 22:19 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
> +                _logger.debug(key)
Done

2024-03-13 22:19 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
>              for key in self.__dict__.keys():
Done

2024-03-13 22:21 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +        _logger.debug("%s %s", self.f.size,self.time.size)
Done

2024-03-13 22:22 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_spectrum_ph3.py
> +        _logger.debug('mean variance of timeseries chunks: ',self.chunks.var(axis=1).mean() if self.save_chunks is True else 'data not saved')
Done

2024-03-13 22:22 UTC, hollandjg commented on src/icesat2_tracks/local_modules/m_general_ph3.py
Thanks!

2024-03-14 14:56 UTC, cpaniaguam requested changes
Thanks for this, John!

I noted some files that are not uniformly formatted. Also, there seems to be another logging mechanism in place already. It might be worth giving some thought to how this new logger is going to interact with the existing one.

2024-03-14 14:56 UTC, cpaniaguam commented on src/icesat2waves/local_modules/jonswap_gamma.py
Add more context here?

2024-03-14 14:56 UTC, cpaniaguam commented on src/icesat2waves/local_modules/m_general_ph3.py
> +            _logger.debug("self.iter2")
Consider adding more context to these.

2024-03-14 14:56 UTC, cpaniaguam commented on src/icesat2waves/local_modules/m_general_ph3.py
> +            _logger.debug("%s %s", line_left[0], time_lin[0])
These could benefit from adding a bit more context.

2024-03-14 14:56 UTC, cpaniaguam commented on src/icesat2waves/local_modules/m_general_ph3.py
> +            _logger.debug("line_right[-1]: %s, time_lin[-1]: %s", line_right[-1], time_lin[-1])
Maybe something like this could be done to the ones above.

2024-03-14 14:56 UTC, cpaniaguam commented on src/icesat2waves/local_modules/m_general_ph3.py
> +            _logger.debug("%s %s",line_right[-1], time_lin[-1])
Also here.

2024-03-14 14:56 UTC, cpaniaguam commented on src/icesat2waves/local_modules/m_spectrum_ph3.py
>              MT.write_log(self.hist, "window")
Have you given some thought about how this logger is interacting with this other logger?

2024-03-14 14:56 UTC, cpaniaguam commented on src/icesat2waves/local_modules/m_spectrum_ph3.py
>          M.echo_dt(timeres)
What about these instances of logging?

2024-03-14 14:56 UTC, cpaniaguam commented on src/icesat2waves/local_modules/m_tools_ph3.py
> +        _logger.debug("%s", hist + message if verbose == 'all' else message)
Add more context here?

2024-03-15 14:54 UTC, hollandjg commented on src/icesat2waves/local_modules/jonswap_gamma.py
Done

2024-03-15 14:56 UTC, hollandjg commented on src/icesat2waves/local_modules/m_colormanager_ph3.py
> +                _logger.debug("%s",key)
I'm not sure what the context here should be.

2024-03-15 14:57 UTC, cpaniaguam commented on src/icesat2waves/local_modules/m_colormanager_ph3.py
> +                _logger.debug("%s",key)
What about something like this:
```suggestion
                _logger.debug("key: %s", key)
```

2024-03-15 14:59 UTC, hollandjg commented on src/icesat2waves/local_modules/m_general_ph3.py
> +        _logger.debug(string)
I think the context comes from the string – it's a delta time object, and I think the context will be supplied by the calling function.

2024-03-15 15:00 UTC, hollandjg commented on src/icesat2waves/local_modules/m_general_ph3.py
> +        _logger.debug("error")
Yes

2024-03-15 15:14 UTC, hollandjg commented on src/icesat2waves/local_modules/m_general_ph3.py
> +        _logger.debug("error")
Done

2024-03-15 15:16 UTC, hollandjg commented on src/icesat2waves/local_modules/m_general_ph3.py
> +            _logger.debug("self.iter2")
This function is totally broken anyway, and I'm not sure what context to add here.

2024-03-15 15:17 UTC, hollandjg commented on src/icesat2waves/local_modules/m_general_ph3.py
> +            _logger.debug("%s %s", line_left[0], time_lin[0])
Added above the block

2024-03-15 15:17 UTC, hollandjg commented on src/icesat2waves/local_modules/m_general_ph3.py
> +            _logger.debug("%s %s",line_right[-1], time_lin[-1])
Added above

2024-03-15 15:18 UTC, cpaniaguam commented on src/icesat2waves/local_modules/m_general_ph3.py
> +            _logger.debug("self.iter2")
Maybe something like `_logger.debug("iter2: %s", self.iter2)`?

2024-03-15 15:24 UTC, hollandjg commented on src/icesat2waves/local_modules/m_general_ph3.py
> +            _logger.debug("line_right[-1]: %s, time_lin[-1]: %s", line_right[-1], time_lin[-1])
Done

2024-03-15 15:25 UTC, hollandjg commented on src/icesat2waves/local_modules/m_spectrum_ph3.py
>              MT.write_log(self.hist, "window")
The other logger uses _logger.debug within its function, so we're fine here.

2024-03-15 15:26 UTC, hollandjg commented on src/icesat2waves/local_modules/m_spectrum_ph3.py
>          M.echo_dt(timeres)
Echo_dt also uses _logger.debug

2024-03-15 15:27 UTC, hollandjg commented on src/icesat2waves/local_modules/m_tools_ph3.py
> +        _logger.debug("%s", hist + message if verbose == 'all' else message)
Done

2024-03-15 17:02 UTC, cpaniaguam requested changes
Just two observations.

2024-03-15 17:02 UTC, cpaniaguam commented on src/icesat2waves/local_modules/m_tools_ph3.py
> +        _logger.debug("shape of %s: %s", i, i.shape)
```suggestion
        _logger.debug("shape of i=%s: %s", i, i.shape)
```

2024-03-18 14:10 UTC, kmilo9999 commented on src/icesat2waves/local_modules/m_general_ph3.py
> +        _logger.debug("iindex: %s", iindex)
```suggestion
        _logger.debug("index: %s", iindex)
```

2024-03-18 14:12 UTC, kmilo9999 approved these changes
Looks good to me. There is  small change I suggeted

2024-03-18 17:16 UTC, hollandjg commented on src/icesat2waves/local_modules/m_general_ph3.py
> +        _logger.debug("iindex: %s", iindex)
Done!

2024-03-18 17:17 UTC, hollandjg commented on src/icesat2waves/local_modules/m_tools_ph3.py
> +        _logger.debug("shape of %s: %s", i, i.shape)
Done both of these.

2024-03-19 23:23 UTC, cpaniaguam submitted a review, later dismissed
Thanks!

2024-03-22 14:12 UTC, merged