chore: reformat all the files using black
brown-ccv/icesat2waves pull request #198
Opened 2024-03-14 16:48 UTC by hollandjg

Reformat everything using black.

2024-03-14 19:23 UTC, cpaniaguam requested changes
Couple of new lines at the end of files and typo.

2024-03-14 19:23 UTC, cpaniaguam commented on src/icesat2waves/__init__.py
> +"""Tools to analyse data from ICESat-2."""
```suggestion
"""Tools to analyse data from ICESat-2."""

```

2024-03-14 19:23 UTC, cpaniaguam commented on src/icesat2waves/config/__init__.py
> +"""Configuration file containing project paths"""
```suggestion
"""Configuration file containing project paths"""

```

2024-03-14 19:23 UTC, cpaniaguam commented on src/icesat2waves/local_modules/__init__.py
> +"""Utility functions to manage parameters to plot results"""
```suggestion
"""Utility functions to manage parameters to plot results"""

```

2024-03-14 19:23 UTC, cpaniaguam commented on src/icesat2waves/tools/__init__.py
> +"Utility functions for loading files/data and tools for ploting tables and figures "
```suggestion
"Utility functions for loading files/data and tools for plotting tables and figures "

```

2024-03-15 14:48 UTC, hollandjg commented on src/icesat2waves/tools/__init__.py
> +"Utility functions for loading files/data and tools for ploting tables and figures "
I think the newline is already included, it just doesn't show up as a line number (if it were missing, then it would show up as a red circle with a line, as in the diff on the left in the changes viewer.
<img width="655" alt="Screenshot 2024-03-15 at 10 47 24" src="https://github.com/brown-ccv/icesat2waves/assets/2803227/574f42d4-8610-4885-968d-2432e305dd8e">
<img width="611" alt="Screenshot 2024-03-15 at 10 47 27" src="https://github.com/brown-ccv/icesat2waves/assets/2803227/5ecaf1a3-957d-4845-a0f6-421e6090a823">

2024-03-15 14:48 UTC, hollandjg commented on src/icesat2waves/__init__.py
> +"""Tools to analyse data from ICESat-2."""
I think the newline is already included, it just doesn't show up directly as a line-number in the window. (More detailed comment with screenshots below.)

2024-03-15 14:49 UTC, hollandjg commented on src/icesat2waves/config/__init__.py
> +"""Configuration file containing project paths"""
Ditto.

2024-03-15 14:49 UTC, hollandjg commented on src/icesat2waves/local_modules/__init__.py
> +"""Utility functions to manage parameters to plot results"""
Ditto

2024-03-15 15:41 UTC, cpaniaguam submitted a review, later dismissed

2024-03-15 15:41 UTC, cpaniaguam commented on src/icesat2waves/__init__.py
> +"""Tools to analyse data from ICESat-2."""
I am looking at the file and it says it only has one line. Look for yourself here https://github.com/brown-ccv/icesat2waves/blob/ef9e9f153511f5fc4f2a06f61bf62d4452b5bea4/src/icesat2waves/__init__.py:
![image](https://github.com/brown-ccv/icesat2waves/assets/68481491/ca5ee975-286e-4649-9034-6e47ff93a550)

Is this a bug or something?

2024-03-22 14:12 UTC, merged